apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres-mwdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-mwdb
  strategy: {}
  template:
    metadata:
      labels:
        app: postgres-mwdb
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: postgres-vars-env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: postgres-vars-env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: postgres-vars-env
          image: postgres
          name: postgres-mwdb
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "300m"          
      restartPolicy: Always
status: {}
